const webList:{name:string,key:string,address?:string}[] = [
  {
    name:'起点中文网',
    key:'qidian',
    address:'https://www.qidian.com/'
  },
  {
    name:'飞卢小说',
    key:'feilu',
    address:'https://www.faloo.com/'
  },
  {
    name:'番茄免费小说',
    key:'fanqie',
    address:'https://fanqienovel.com/'
  },
  {
    name:'七猫免费小说',
    key:'qimao',  
    address:'https://www.qimao.com/'
  },
  {
    name:'掌阅小说',
    key:'zhangyue',
    address:'https://www.ireader.com.cn/'
  },
  {
    name:'QQ阅读',
    key:'qq',
    address:'https://book.qq.com/'
  },

  {
    name:'书旗小说',
    key:'shuqi',
    address:'https://www.shuqi.com/'
  },
  {
    name:'17K',
    key:'17k',
    address:'https://www.17k.com/'
  },
  {
    name:'塔读小说',
    key:'tadu',
    address:'https://www.tadu.com/'
  },
  {
    name:'刺猬猫小说',
    key:'ciweimao',
    address:'https://www.ciweimao.com/'
  },
  {
    name:'火星',
    key:'huoxing',
    address:'https://mobile.hotread.com/'
  },
  {
    name:'铁血',
    key:'tiexue',
    address:'https://book.tiexue.net/'
  },
  {
    name:'磨铁',
    key:'motie',
    address:'https://www.laikan.com/wenxue#'
  },
  {
    name:'爱奇艺',
    key:'aiqiyi',
    address:'https://wenxue.iqiyi.com/'
  },
  {
    name:'趣阅',
    key:'quyue',
    address:'https://www.quyuewang.cn/'
  },
]

export default webList